name: Deploy to Localhost via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2000 -H 192.168.1.6 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -p 2000 -i ~/.ssh/id_rsa clown69@192.168.1.6 << 'EOF'
            cd "/home/clown69/dicoding/Submission 1 Menjadi Back-End Developer Expert dengan JavaScript"
            git pull origin master
            npm install
            npm run migrate up
            pm2 restart forum-api || npm run start
          EOF
