name: Continuous Deployment

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd "/home/deployer/dicoding/Submission 1 Menjadi Back-End Developer Expert dengan JavaScript"
          git pull origin master
          npm install
          npm run migrate up
          pm2 restart forum-api
