name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 sequence-leader-dietary-webshots.trycloudflare.com >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 clown69@sequence-leader-dietary-webshots.trycloudflare.com << 'EOF'
            cd "/home/clown69/dicoding/Submission 1 Menjadi Back-End Developer Expert dengan JavaScript"
            git pull origin master
            npm install
            npm run migrate up
            pm2 restart forum-api || npm run start
          EOF
