name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 13525 0.tcp.ap.ngrok.io >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -p 13525 clown69@0.tcp.ap.ngrok.io << 'EOF'
            cd "/home/deployer/dicoding/Submission 1 Menjadi Back-End Developer Expert dengan JavaScript"
            git pull origin master
            npm install
            npm run migrate up
            pm2 restart forum-api || npm run start
          EOF
